### ISSUE TITLE
Possible typo in RangeFinder.cpp

### ISSUE THREAD

**Issue by yutuofish2** [Samsonsjarkal/LLAP#1]
In RangeFinder.cpp, line 263-264, 451-452

 mDCValue[i][f]=(1-DC_TREND*2)*mDCValue[i][f]+
                    (mMinValue[i][f]+mMinValue[i][f])/2*DC_TREND*2;

shouldn't it be 
mDCValue[i][f]=(1-DC_TREND*2)*mDCValue[i][f]+
                    (mMinValue[i][f]+**mMaxValue**[i][f])/2*DC_TREND*2;

**Comment by Samsonsjarkal** [comment]
Thanks! We have modified our typo.
