### ISSUE TITLE
Amazing Work! 

### ISSUE THREAD

**Issue by theeagleofthedesert** [Samsonsjarkal/LLAP#2]
I'm trying to use ultrasound on my android phone, so could you share an implementation of LLAP in Android?

**Comment by heeler-deer** [comment]
> I'm trying to use ultrasound on my android phone, so could you share an implementation of LLAP in Android?

https://github.com/MangoForest/LLAP
this one

**Comment by theeagleofthedesert** [comment]
> > I'm trying to use ultrasound on my android phone, so could you share an implementation of LLAP in Android?
> 
> https://github.com/MangoForest/LLAP this one

Thank you!
